### ISSUE TITLE
Error: Cannot find table on the account statement page 

### ISSUE THREAD

**Issue by Fonnte** [ammarfaizi2/KlikBCA#2]
untuk pengambilan pertama kali berhasil. tapi setelah dicoba lagi jadi error  : 

Error: Cannot find table on the account statement page

pada halaman ibank terkena limit. 

![Screenshot_6](https://user-images.githubusercontent.com/23734341/168420262-2370813a-db0c-4c29-8a80-04e693aef7e5.png)
 
 ada solusi?

**Comment by alviroiskandar** [comment]
kek nya cuma bisa nunggu sampe limit na lepas deh, klo menghindari na berarti jangan jalanin ini berlebihan

**Comment by ammarfaizi2** [comment]
Belum ada solusi untuk ini. Kalau terkena limit harus menunggu limitnya lepas.

**Comment by Fonnte** [comment]
Wah, padahal sy cuma refresh aja sekali, jd run 2x sih. Berarti emang dari bca nya ya

**Comment by ammarfaizi2** [comment]
> Wah, padahal sy cuma refresh aja sekali, jd run 2x sih. Berarti emang dari bca nya ya

Aneh, tapi kalau di tempat saya, saya jalankan cek saldo dan mutasi,
looping 20 kali tanpa berhenti nggak kena limit:

```bash
# Pakai bash shell
for i in {1..20}; do php run.php; done;
```

Saya sendiri belum pernah kena limit sejauh ini.

Beberapa orang tadi ada yang bilang juga kena limit juga di komentar
Facebook. Tapi jumlah run-nya variatif, ada yang bilang 10x concurrent
requests baru kena limit.

Link Facebook comment: https://fb.com/3029687893915369

**Comment by Fonnte** [comment]
sepertinya update terakhir sudah bisa jalan normal, saya coba beberapa kali udah lancar nih mas gak masalah. good job!
